### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by yingchengyang** [TEA-Lab/diffusion_reward#3]
Thanks a lot such a wonderful work! I'm curious about the dataset. First, how can we download the datasets from Hugging Face? Can we directly use the library Datasets? Moreover, if we want to consider other RL tasks with videos, what format should our dataset adopt? It seems that the dataset is like all figures, is it right?

Thanks again!

**Comment by TaoHuang13** [comment]
Hi, Thanks for your interest in our work.

Please consider [this document ](https://huggingface.co/docs/hub/datasets-downloading) for downloading our dataset. We suggest using our dataset to reproduce results, though, other datasets could be used depending on your intent.

For dataset format, yes, we only use images. You are encouraged to transform the format of your dataset into one like ours for running code successfully. This will save the time in rewriting the dataloader.

**Comment by yingchengyang** [comment]
Thanks a lot! It seems that every episode obtains around 30 frames, what is the action repeat during sampling trajectories? Thanks again

**Comment by TaoHuang13** [comment]
Hi. Please refer to Table 6 in the Appendix of the paper. We set 2 for Adroit and 3 for MetaWorld.

**Comment by yingchengyang** [comment]
Thanks a lot!
