### ISSUE TITLE
About Quantitative comparison of video models

### ISSUE THREAD

**Issue by yingchengyang** [TEA-Lab/diffusion_reward#8]
Thanks a lot for such a wonderful work! I'm curious about the Quantitative comparison of different video models (like videogpt and vqdiffusion) in table 1 of the paper. How can I evaluate the performance of video models? Thanks a lot!

**Comment by luccachiang** [comment]
Hi! Thanks for your interest. The results are calculated by generated videos and their _ground truths_. In our case, we give one video, i.e. _ground truth_, as a condition to the model to generate one corresponding video. As for metric calculation, please kindly refer to [this repo](https://github.com/JunyaoHu/common_metrics_on_video_quality) for more details :)
